export const lessons = [
    {
      id: 1,
      subject: "Mathematics",
      location: "London",
      price: "£100",
      spaces: 5,
    },
    {
      id: 2,
      subject: "English",
      location: "Birmingham",
      price: "£50",
      spaces: 5,
    },
    {
      id: 3,
      subject: "Science",
      location: "Edinburgh",
      price: "£140",
      spaces: 5,
    },
    {
      id: 4,
      subject: "Mathematics",
      location: "Hendon, London",
      price: "£100",
      spaces: 5,
    },
    {
      id: 5,
      subject: "Ux Design",
      location: "Golder's Green",
      price: "£10",
      spaces: 5,
    },
    {
      id: 6,
      subject: "Computer",
      location: "Tottenham",
      price: "£190",
      spaces: 5,
    },
    {
      id: 7,
      subject: "Web Dev",
      location: "London",
      price: "£100",
      spaces: 5,
    },
    {
      id: 8,
      subject: "Mathematics",
      location: "Hendon, London",
      price: "£100",
      spaces: 5,
    },
    {
      id: 9,
      subject: "Mathematics",
      location: "Hendon, London",
      price: "£100",
      spaces: 5,
    },
    {
      id: 10,
      subject: "Mathematics",
      location: "Hendon, London",
      price: "£100",
      spaces: 5,
    },
    {
      id: 11,
      subject: "Mathematics",
      location: "Hendon, London",
      price: "£100",
      spaces: 5,
    },
    {
      id: 12,
      subject: "Mathematics",
      location: "Hendon, London",
      price: "£100",
      spaces: 5,
    },
  ]